// Automatically generated by service-generator.js, don't change!
import { BaseService } from './base-service';
import { Track } from '../models';

/**
 * Control the sonos alarms
 *
 * @export
 * @class AlarmClockService
 * @extends {BaseService}
 */
export class AlarmClockService extends BaseService {
  readonly serviceNane: string = 'AlarmClock';
  readonly controlUrl: string = '/AlarmClock/Control';  
  readonly eventSubUrl: string = '/AlarmClock/Event';
  readonly scpUrl: string = '/xml/AlarmClock1.xml';

  //#region methods
  async CreateAlarm(input: { StartLocalTime: string; Duration: string; Recurrence: string; Enabled: boolean; RoomUUID: string; ProgramURI: string; ProgramMetaData: string | Track; PlayMode: string; Volume: number; IncludeLinkedZones: boolean }):
    Promise<CreateAlarmResponse>{ return await this.SoapRequestWithBody<typeof input, CreateAlarmResponse>('CreateAlarm', input); }

  async DestroyAlarm(input: { ID: number }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('DestroyAlarm', input); }

  async GetDailyIndexRefreshTime():
    Promise<GetDailyIndexRefreshTimeResponse>{ return await this.SoapRequest<GetDailyIndexRefreshTimeResponse>('GetDailyIndexRefreshTime'); }

  async GetFormat():
    Promise<GetFormatResponse>{ return await this.SoapRequest<GetFormatResponse>('GetFormat'); }

  async GetHouseholdTimeAtStamp(input: { TimeStamp: string }):
    Promise<GetHouseholdTimeAtStampResponse>{ return await this.SoapRequestWithBody<typeof input, GetHouseholdTimeAtStampResponse>('GetHouseholdTimeAtStamp', input); }

  async GetTimeNow():
    Promise<GetTimeNowResponse>{ return await this.SoapRequest<GetTimeNowResponse>('GetTimeNow'); }

  async GetTimeServer():
    Promise<GetTimeServerResponse>{ return await this.SoapRequest<GetTimeServerResponse>('GetTimeServer'); }

  async GetTimeZone():
    Promise<GetTimeZoneResponse>{ return await this.SoapRequest<GetTimeZoneResponse>('GetTimeZone'); }

  async GetTimeZoneAndRule():
    Promise<GetTimeZoneAndRuleResponse>{ return await this.SoapRequest<GetTimeZoneAndRuleResponse>('GetTimeZoneAndRule'); }

  async GetTimeZoneRule(input: { Index: number }):
    Promise<GetTimeZoneRuleResponse>{ return await this.SoapRequestWithBody<typeof input, GetTimeZoneRuleResponse>('GetTimeZoneRule', input); }

  async ListAlarms():
    Promise<ListAlarmsResponse>{ return await this.SoapRequest<ListAlarmsResponse>('ListAlarms'); }

  async SetDailyIndexRefreshTime(input: { DesiredDailyIndexRefreshTime: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('SetDailyIndexRefreshTime', input); }

  async SetFormat(input: { DesiredTimeFormat: string; DesiredDateFormat: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('SetFormat', input); }

  async SetTimeNow(input: { DesiredTime: string; TimeZoneForDesiredTime: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('SetTimeNow', input); }

  async SetTimeServer(input: { DesiredTimeServer: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('SetTimeServer', input); }

  async SetTimeZone(input: { Index: number; AutoAdjustDst: boolean }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('SetTimeZone', input); }

  async UpdateAlarm(input: { ID: number; StartLocalTime: string; Duration: string; Recurrence: string; Enabled: boolean; RoomUUID: string; ProgramURI: string; ProgramMetaData: string | Track; PlayMode: string; Volume: number; IncludeLinkedZones: boolean }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('UpdateAlarm', input); }
  //#endregion
}

// Generated responses
export interface CreateAlarmResponse {
  AssignedID: number;
}

export interface GetDailyIndexRefreshTimeResponse {
  CurrentDailyIndexRefreshTime: string;
}

export interface GetFormatResponse {
  CurrentTimeFormat: string;
  CurrentDateFormat: string;
}

export interface GetHouseholdTimeAtStampResponse {
  HouseholdUTCTime: string;
}

export interface GetTimeNowResponse {
  CurrentUTCTime: string;
  CurrentLocalTime: string;
  CurrentTimeZone: string;
  CurrentTimeGeneration: number;
}

export interface GetTimeServerResponse {
  CurrentTimeServer: string;
}

export interface GetTimeZoneResponse {
  Index: number;
  AutoAdjustDst: boolean;
}

export interface GetTimeZoneAndRuleResponse {
  Index: number;
  AutoAdjustDst: boolean;
  CurrentTimeZone: string;
}

export interface GetTimeZoneRuleResponse {
  TimeZone: string;
}

export interface ListAlarmsResponse {
  CurrentAlarmList: string;
  CurrentAlarmListVersion: string;
}
