// Automatically generated by service-generator.js, don't change!
import { BaseService } from './base-service';
import { BrowseResponse } from '../models';

/**
 * Browse for local content
 *
 * @export
 * @class ContentDirectoryService
 * @extends {BaseService}
 */
export class ContentDirectoryService extends BaseService {
  readonly serviceNane: string = 'ContentDirectory';
  readonly controlUrl: string = '/MediaServer/ContentDirectory/Control';  
  readonly eventSubUrl: string = '/MediaServer/ContentDirectory/Event';
  readonly scpUrl: string = '/xml/ContentDirectory1.xml';

  //#region methods
  async Browse(input: { ObjectID: string; BrowseFlag: string; Filter: string; StartingIndex: number; RequestedCount: number; SortCriteria: string }):
    Promise<BrowseResponse>{ return await this.SoapRequestWithBody<typeof input, BrowseResponse>('Browse', input); }

  async CreateObject(input: { ContainerID: string; Elements: string }):
    Promise<CreateObjectResponse>{ return await this.SoapRequestWithBody<typeof input, CreateObjectResponse>('CreateObject', input); }

  async DestroyObject(input: { ObjectID: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('DestroyObject', input); }

  async FindPrefix(input: { ObjectID: string; Prefix: string }):
    Promise<FindPrefixResponse>{ return await this.SoapRequestWithBody<typeof input, FindPrefixResponse>('FindPrefix', input); }

  async GetAlbumArtistDisplayOption():
    Promise<GetAlbumArtistDisplayOptionResponse>{ return await this.SoapRequest<GetAlbumArtistDisplayOptionResponse>('GetAlbumArtistDisplayOption'); }

  async GetAllPrefixLocations(input: { ObjectID: string }):
    Promise<GetAllPrefixLocationsResponse>{ return await this.SoapRequestWithBody<typeof input, GetAllPrefixLocationsResponse>('GetAllPrefixLocations', input); }

  async GetBrowseable():
    Promise<GetBrowseableResponse>{ return await this.SoapRequest<GetBrowseableResponse>('GetBrowseable'); }

  async GetLastIndexChange():
    Promise<GetLastIndexChangeResponse>{ return await this.SoapRequest<GetLastIndexChangeResponse>('GetLastIndexChange'); }

  async GetSearchCapabilities():
    Promise<GetSearchCapabilitiesResponse>{ return await this.SoapRequest<GetSearchCapabilitiesResponse>('GetSearchCapabilities'); }

  async GetShareIndexInProgress():
    Promise<GetShareIndexInProgressResponse>{ return await this.SoapRequest<GetShareIndexInProgressResponse>('GetShareIndexInProgress'); }

  async GetSortCapabilities():
    Promise<GetSortCapabilitiesResponse>{ return await this.SoapRequest<GetSortCapabilitiesResponse>('GetSortCapabilities'); }

  async GetSystemUpdateID():
    Promise<GetSystemUpdateIDResponse>{ return await this.SoapRequest<GetSystemUpdateIDResponse>('GetSystemUpdateID'); }

  async RefreshShareIndex(input: { AlbumArtistDisplayOption: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('RefreshShareIndex', input); }

  async RequestResort(input: { SortOrder: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('RequestResort', input); }

  async SetBrowseable(input: { Browseable: boolean }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('SetBrowseable', input); }

  async UpdateObject(input: { ObjectID: string; CurrentTagValue: string; NewTagValue: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('UpdateObject', input); }
  //#endregion
}

// Generated responses
export interface CreateObjectResponse {
  ObjectID: string;
  Result: string;
}

export interface FindPrefixResponse {
  StartingIndex: number;
  UpdateID: number;
}

export interface GetAlbumArtistDisplayOptionResponse {
  AlbumArtistDisplayOption: string;
}

export interface GetAllPrefixLocationsResponse {
  TotalPrefixes: number;
  PrefixAndIndexCSV: string;
  UpdateID: number;
}

export interface GetBrowseableResponse {
  IsBrowseable: boolean;
}

export interface GetLastIndexChangeResponse {
  LastIndexChange: string;
}

export interface GetSearchCapabilitiesResponse {
  SearchCaps: string;
}

export interface GetShareIndexInProgressResponse {
  IsIndexing: boolean;
}

export interface GetSortCapabilitiesResponse {
  SortCaps: string;
}

export interface GetSystemUpdateIDResponse {
  Id: number;
}
