// Automatically generated by service-generator.js, don't change!
import { BaseService } from './base-service';

/**
 * Modify device properties, like led status and stereo pairs
 *
 * @export
 * @class DevicePropertiesService
 * @extends {BaseService}
 */
export class DevicePropertiesService extends BaseService {
  readonly serviceNane: string = 'DeviceProperties';
  readonly controlUrl: string = '/DeviceProperties/Control';  
  readonly eventSubUrl: string = '/DeviceProperties/Event';
  readonly scpUrl: string = '/xml/DeviceProperties1.xml';

  //#region methods
  async AddBondedZones(input: { ChannelMapSet: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('AddBondedZones', input); }

  async AddHTSatellite(input: { HTSatChanMapSet: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('AddHTSatellite', input); }

  async CreateStereoPair(input: { ChannelMapSet: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('CreateStereoPair', input); }

  async EnterConfigMode(input: { Mode: string; Options: string }):
    Promise<EnterConfigModeResponse>{ return await this.SoapRequestWithBody<typeof input, EnterConfigModeResponse>('EnterConfigMode', input); }

  async ExitConfigMode(input: { Options: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('ExitConfigMode', input); }

  async GetAutoplayLinkedZones(input: { Source: string }):
    Promise<GetAutoplayLinkedZonesResponse>{ return await this.SoapRequestWithBody<typeof input, GetAutoplayLinkedZonesResponse>('GetAutoplayLinkedZones', input); }

  async GetAutoplayRoomUUID(input: { Source: string }):
    Promise<GetAutoplayRoomUUIDResponse>{ return await this.SoapRequestWithBody<typeof input, GetAutoplayRoomUUIDResponse>('GetAutoplayRoomUUID', input); }

  async GetAutoplayVolume(input: { Source: string }):
    Promise<GetAutoplayVolumeResponse>{ return await this.SoapRequestWithBody<typeof input, GetAutoplayVolumeResponse>('GetAutoplayVolume', input); }

  async GetButtonLockState():
    Promise<GetButtonLockStateResponse>{ return await this.SoapRequest<GetButtonLockStateResponse>('GetButtonLockState'); }

  async GetButtonState():
    Promise<GetButtonStateResponse>{ return await this.SoapRequest<GetButtonStateResponse>('GetButtonState'); }

  async GetHouseholdID():
    Promise<GetHouseholdIDResponse>{ return await this.SoapRequest<GetHouseholdIDResponse>('GetHouseholdID'); }

  async GetLEDState():
    Promise<GetLEDStateResponse>{ return await this.SoapRequest<GetLEDStateResponse>('GetLEDState'); }

  async GetUseAutoplayVolume(input: { Source: string }):
    Promise<GetUseAutoplayVolumeResponse>{ return await this.SoapRequestWithBody<typeof input, GetUseAutoplayVolumeResponse>('GetUseAutoplayVolume', input); }

  async GetZoneAttributes():
    Promise<GetZoneAttributesResponse>{ return await this.SoapRequest<GetZoneAttributesResponse>('GetZoneAttributes'); }

  async GetZoneInfo():
    Promise<GetZoneInfoResponse>{ return await this.SoapRequest<GetZoneInfoResponse>('GetZoneInfo'); }

  async RemoveBondedZones(input: { ChannelMapSet: string; KeepGrouped: boolean }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('RemoveBondedZones', input); }

  async RemoveHTSatellite(input: { SatRoomUUID: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('RemoveHTSatellite', input); }

  async SeparateStereoPair(input: { ChannelMapSet: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('SeparateStereoPair', input); }

  async SetAutoplayLinkedZones(input: { IncludeLinkedZones: boolean; Source: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('SetAutoplayLinkedZones', input); }

  async SetAutoplayRoomUUID(input: { RoomUUID: string; Source: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('SetAutoplayRoomUUID', input); }

  async SetAutoplayVolume(input: { Volume: number; Source: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('SetAutoplayVolume', input); }

  async SetButtonLockState(input: { DesiredButtonLockState: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('SetButtonLockState', input); }

  async SetLEDState(input: { DesiredLEDState: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('SetLEDState', input); }

  async SetUseAutoplayVolume(input: { UseVolume: boolean; Source: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('SetUseAutoplayVolume', input); }

  async SetZoneAttributes(input: { DesiredZoneName: string; DesiredIcon: string; DesiredConfiguration: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('SetZoneAttributes', input); }
  //#endregion
}

// Generated responses
export interface EnterConfigModeResponse {
  State: string;
}

export interface GetAutoplayLinkedZonesResponse {
  IncludeLinkedZones: boolean;
}

export interface GetAutoplayRoomUUIDResponse {
  RoomUUID: string;
}

export interface GetAutoplayVolumeResponse {
  CurrentVolume: number;
}

export interface GetButtonLockStateResponse {
  CurrentButtonLockState: string;
}

export interface GetButtonStateResponse {
  State: string;
}

export interface GetHouseholdIDResponse {
  CurrentHouseholdID: string;
}

export interface GetLEDStateResponse {
  CurrentLEDState: string;
}

export interface GetUseAutoplayVolumeResponse {
  UseVolume: boolean;
}

export interface GetZoneAttributesResponse {
  CurrentZoneName: string;
  CurrentIcon: string;
  CurrentConfiguration: string;
}

export interface GetZoneInfoResponse {
  SerialNumber: string;
  SoftwareVersion: string;
  DisplaySoftwareVersion: string;
  HardwareVersion: string;
  IPAddress: string;
  MACAddress: string;
  CopyrightInfo: string;
  ExtraInfo: string;
  HTAudioIn: number;
  Flags: number;
}
