// Automatically generated by service-generator.js, don't change!
import BaseService from './base-service';

export class SystemPropertiesServiceBase extends BaseService<SystemPropertiesServiceEvent> {
  readonly serviceNane: string = 'SystemProperties';

  readonly controlUrl: string = '/SystemProperties/Control';

  readonly eventSubUrl: string = '/SystemProperties/Event';

  readonly scpUrl: string = '/xml/SystemProperties1.xml';

  // #region methods
  async AddAccountX(input: { AccountType: number; AccountID: string; AccountPassword: string }):
  Promise<AddAccountXResponse> { return await this.SoapRequestWithBody<typeof input, AddAccountXResponse>('AddAccountX', input); }

  async AddOAuthAccountX(input: { AccountType: number; AccountToken: string; AccountKey: string; OAuthDeviceID: string; AuthorizationCode: string; RedirectURI: string; UserIdHashCode: string; AccountTier: number }):
  Promise<AddOAuthAccountXResponse> { return await this.SoapRequestWithBody<typeof input, AddOAuthAccountXResponse>('AddOAuthAccountX', input); }

  async DoPostUpdateTasks():
  Promise<boolean> { return await this.SoapRequestNoResponse('DoPostUpdateTasks'); }

  async EditAccountMd(input: { AccountType: number; AccountID: string; NewAccountMd: string }):
  Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('EditAccountMd', input); }

  async EditAccountPasswordX(input: { AccountType: number; AccountID: string; NewAccountPassword: string }):
  Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('EditAccountPasswordX', input); }

  async EnableRDM(input: { RDMValue: boolean }):
  Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('EnableRDM', input); }

  async GetRDM():
  Promise<GetRDMResponse> { return await this.SoapRequest<GetRDMResponse>('GetRDM'); }

  async GetString(input: { VariableName: string }):
  Promise<GetStringResponse> { return await this.SoapRequestWithBody<typeof input, GetStringResponse>('GetString', input); }

  async GetWebCode(input: { AccountType: number }):
  Promise<GetWebCodeResponse> { return await this.SoapRequestWithBody<typeof input, GetWebCodeResponse>('GetWebCode', input); }

  async ProvisionCredentialedTrialAccountX(input: { AccountType: number; AccountID: string; AccountPassword: string }):
  Promise<ProvisionCredentialedTrialAccountXResponse> { return await this.SoapRequestWithBody<typeof input, ProvisionCredentialedTrialAccountXResponse>('ProvisionCredentialedTrialAccountX', input); }

  async RefreshAccountCredentialsX(input: { AccountType: number; AccountUID: number; AccountToken: string; AccountKey: string }):
  Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('RefreshAccountCredentialsX', input); }

  async Remove(input: { VariableName: string }):
  Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('Remove', input); }

  async RemoveAccount(input: { AccountType: number; AccountID: string }):
  Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('RemoveAccount', input); }

  async ReplaceAccountX(input: { AccountUDN: string; NewAccountID: string; NewAccountPassword: string; AccountToken: string; AccountKey: string; OAuthDeviceID: string }):
  Promise<ReplaceAccountXResponse> { return await this.SoapRequestWithBody<typeof input, ReplaceAccountXResponse>('ReplaceAccountX', input); }

  async ResetThirdPartyCredentials():
  Promise<boolean> { return await this.SoapRequestNoResponse('ResetThirdPartyCredentials'); }

  async SetAccountNicknameX(input: { AccountUDN: string; AccountNickname: string }):
  Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('SetAccountNicknameX', input); }

  async SetString(input: { VariableName: string; StringValue: string }):
  Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('SetString', input); }
  // #endregion

  // Event properties from service description.
  protected eventProperties(): {[key: string]: string} {
    return {
      CustomerID: 'string',
      ThirdPartyHash: 'string',
      UpdateID: 'number',
      UpdateIDX: 'number',
      VoiceUpdateID: 'number',
    };
  }
}

// Generated responses
export interface AddAccountXResponse {
  AccountUDN: string;
}

export interface AddOAuthAccountXResponse {
  AccountUDN: string;
  AccountNickname: string;
}

export interface GetRDMResponse {
  RDMValue: boolean;
}

export interface GetStringResponse {
  StringValue: string;
}

export interface GetWebCodeResponse {
  WebCode: string;
}

export interface ProvisionCredentialedTrialAccountXResponse {
  IsExpired: boolean;
  AccountUDN: string;
}

export interface ReplaceAccountXResponse {
  NewAccountUDN: string;
}

// Strong type event
export interface SystemPropertiesServiceEvent {
  CustomerID?: string;
  ThirdPartyHash?: string;
  UpdateID?: number;
  UpdateIDX?: number;
  VoiceUpdateID?: number;
}

export interface AccountData {
  AuthToken?: string;
  Key?: string;
}

/**
 * Extended SystemPropertiesService, all extensions are to save and load accounts for music services. They should be there, but we cannot load them.
 *
 * @export
 * @class SystemPropertiesService
 * @extends {SystemPropertiesServiceBase}
 */
export class SystemPropertiesService extends SystemPropertiesServiceBase {
  /**
   * Same as GetString, but won't throw if the value isn't found (eg. missing)
   *
   * @param {string} VariableName Name of the variable
   * @returns {(Promise<string | undefined>)} saved value or undefined
   * @memberof SystemPropertiesService
   */
  public async GetStringSafe(VariableName: string): Promise<string | undefined> {
    return await this.GetString({ VariableName })
      .then((resp) => resp.StringValue)
      .catch(() => undefined);
  }

  /**
   * Custom extension to fetch account data, saved by this library
   *
   * @param {string} serviceName Name of the music service, as returned by the MusicServiceService.
   * @returns {(Promise<AccountData | undefined>)} Get the account data or nothing if not saved an account for this service.
   * @memberof SystemPropertiesService
   */
  public async GetAccountData(serviceName: string): Promise<AccountData | undefined> {
    const accounts = await this.SavedAccounts();
    if (accounts?.some((value) => value === serviceName)) {
      return {
        AuthToken: await this.GetStringSafe(`sonos-ts-${serviceName.toLowerCase()}-token`),
        Key: await this.GetStringSafe(`sonos-ts-${serviceName.toLowerCase()}-key`),
      } as AccountData;
    }
    return undefined;
  }

  /**
   * Custom extension to delete an account saved by this library.
   *
   * @param {string} serviceName Name of the music service, as returned by the MusicServiceService.
   * @returns {Promise<boolean>} true if account was found and deleted otherwise false
   * @memberof SystemPropertiesService
   */
  public async DeleteAccount(serviceName: string): Promise<boolean> {
    const accounts = await this.SavedAccounts() ?? [];
    if (accounts.indexOf(serviceName) > -1) {
      const newAccounts = accounts.filter((val) => val !== serviceName);
      await this.SetString({ VariableName: 'sonos-ts-accounts', StringValue: newAccounts.join('|') });
      await this.Remove({ VariableName: `sonos-ts${serviceName.toLowerCase()}-key` });
      await this.Remove({ VariableName: `sonos-ts${serviceName.toLowerCase()}-token` });
      return true;
    }
    return false;
  }

  /**
   * Custom extension to save account login data, in your sonos system.
   *
   * @param {string} serviceName
   * @param {string} token
   * @param {string} key
   * @returns {Promise<boolean>}
   * @memberof SystemPropertiesService
   */
  public async SaveAccount(serviceName: string, key: string, token: string): Promise<boolean> {
    const accounts = await this.SavedAccounts() ?? [];
    if (accounts.indexOf(serviceName) === -1) {
      accounts.push(serviceName);
      accounts.sort();
      await this.SetString({ VariableName: 'sonos-ts-accounts', StringValue: accounts.join('|') });
    }
    await this.SetString({ VariableName: `sonos-ts-${serviceName.toLowerCase()}-token`, StringValue: token });
    await this.SetString({ VariableName: `sonos-ts-${serviceName.toLowerCase()}-key`, StringValue: key });
    return true;
  }

  /**
   * Custom extension to find out saved accounts.
   *
   * @returns {(Promise<string[] | undefined>)}
   * @memberof SystemPropertiesService
   */
  public async SavedAccounts(): Promise<string[] | undefined> {
    const result = await this.GetStringSafe('sonos-ts-accounts');
    return result?.split('|');
  }
}
