// Automatically generated by service-generator.js, don't change!
import { BaseService } from './base-service';

/**
 * Zone config stuff, eg getting all the configured sonos zones.
 *
 * @export
 * @class ZoneGroupTopologyServiceBase
 * @extends {BaseService}
 */
export class ZoneGroupTopologyServiceBase extends BaseService {
  readonly serviceNane: string = 'ZoneGroupTopology';
  readonly controlUrl: string = '/ZoneGroupTopology/Control';  
  readonly eventSubUrl: string = '/ZoneGroupTopology/Event';
  readonly scpUrl: string = '/xml/ZoneGroupTopology1.xml';

  //#region methods
  async BeginSoftwareUpdate(input: { UpdateURL: string; Flags: number; ExtraOptions: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('BeginSoftwareUpdate', input); }

  async CheckForUpdate(input: { UpdateType: string; CachedOnly: boolean; Version: string }):
    Promise<CheckForUpdateResponse>{ return await this.SoapRequestWithBody<typeof input, CheckForUpdateResponse>('CheckForUpdate', input); }

  /**
   * Get information about the current Zone
   */
  async GetZoneGroupAttributes():
    Promise<GetZoneGroupAttributesResponse>{ return await this.SoapRequest<GetZoneGroupAttributesResponse>('GetZoneGroupAttributes'); }

  /**
   * Get all the Sonos groups, (as XML), see GetParsedZoneGroupState
   */
  async GetZoneGroupState():
    Promise<GetZoneGroupStateResponse>{ return await this.SoapRequest<GetZoneGroupStateResponse>('GetZoneGroupState'); }

  async RegisterMobileDevice(input: { MobileDeviceName: string; MobileDeviceUDN: string; MobileIPAndPort: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('RegisterMobileDevice', input); }

  async ReportAlarmStartedRunning():
    Promise<boolean> { return await this.SoapRequestNoResponse('ReportAlarmStartedRunning'); }

  async ReportUnresponsiveDevice(input: { DeviceUUID: string; DesiredAction: string }):
    Promise<boolean> { return await this.SoapRequestWithBodyNoResponse<typeof input>('ReportUnresponsiveDevice', input); }

  async SubmitDiagnostics(input: { IncludeControllers: boolean; Type: string }):
    Promise<SubmitDiagnosticsResponse>{ return await this.SoapRequestWithBody<typeof input, SubmitDiagnosticsResponse>('SubmitDiagnostics', input); }
  //#endregion
}

// Generated responses
export interface CheckForUpdateResponse {
  UpdateItem: string;
}

export interface GetZoneGroupAttributesResponse {
  CurrentZoneGroupName: string;
  CurrentZoneGroupID: string;
  CurrentZonePlayerUUIDsInGroup: string;
  CurrentMuseHouseholdId: string;
}

export interface GetZoneGroupStateResponse {
  ZoneGroupState: string;
}

export interface SubmitDiagnosticsResponse {
  DiagnosticID: number;
}

export interface ZoneGroup {
  name: string;
  coordinator: ZoneMember;
  members: ZoneMember[];
}

interface ZoneMember {
  host: string;
  port: number;
  uuid: string;
  name: string;
}

import { XmlHelper } from '../helpers/xml-helper';
import { ArrayHelper } from '../helpers/array-helper';
import { URL } from 'url'

/**
 * Zone config stuff, eg getting all the configured sonos zones.
 *
 * @export
 * @class ZoneGroupTopologyService
 * @extends {ZoneGroupTopologyServiceBase}
 */
export class ZoneGroupTopologyService extends ZoneGroupTopologyServiceBase {

  /**
   * Get all the sonos groups in your current network. Parsed the GetZoneGroupState output.
   *
   * @returns {Promise<ZoneGroup[]>}
   * @memberof ZoneGroupTopologyService
   */
  async GetParsedZoneGroupState (): Promise<ZoneGroup[]> {
    const groupStateResponse = await this.GetZoneGroupState();
    const decodedGroupState = XmlHelper.DecodeAndParseXml(groupStateResponse.ZoneGroupState)
    const groups = ArrayHelper.ForceArray(decodedGroupState.ZoneGroupState.ZoneGroups.ZoneGroup)
    return groups.map(g => this.ParseGroup(g))
  }

  private ParseMember(member: any): ZoneMember {
    const uri = new URL(member._Location)
    return {
      name: member._ZoneName,
      uuid: member._UUID,
      host: uri.hostname,
      port: parseInt(uri.port)
    }
  }

  private ParseGroup(group: any): ZoneGroup {
    const members: ZoneMember[] = ArrayHelper.ForceArray(group.ZoneGroupMember).map(m => this.ParseMember(m))
    const coordinator: ZoneMember | undefined = members.find(m => m.uuid === group._Coordinator)

    if (coordinator === undefined) throw new Error('Error parsing ZoneGroup')

    let name = coordinator.name
    if(members.length > 1) name += ` + ${members.length - 1}`

    return {
      name: name,
      coordinator: coordinator,
      members: members
    }
  }
}
