blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://sonos-ts.svrooij.io/
    about: Have you checked to documentation?
  - name: Questions
    url: https://github.com/svrooij/node-sonos-ts/discussions/categories/q-a
    about: Not sure how something works, ask a question instead of creating an issue.
