name: Run tests and publish

on:
  push:
    branches:
      - master
      - beta
      # - feature/*
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  release:
    types: [published]

jobs:
  test:
    name: 'Build and test on node v${{ matrix.node }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [24, 26]
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
            node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Run code linting
        run: npm run lint

      - name: Run tests
        if: ${{ always() }}
        run: npm run jest

      - name: Send data to Coveralls
        if: always() && matrix.node == 24
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  npm-publish:
    name: 'Publish to npm'
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'release'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup node for npm registry
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Set version from release tag
        run: npm version --no-git-tag-version "${{ github.event.release.tag_name }}"

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup node for GitHub Package Registry
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://npm.pkg.github.com'
          scope: '@svrooij'

      - name: Publish to GitHub Package Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
